# Generated by Django 3.2 on 2021-04-29 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_app', models.CharField(max_length=120)),
                ('client_id', models.UUIDField(default=uuid.uuid4)),
                ('client_secret', models.UUIDField(default=uuid.uuid4)),
                ('access_token', models.UUIDField(default=uuid.uuid4)),
                ('redirect_url', models.CharField(max_length=120)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
    ]
